global:
  namespace: prod

frontend:
  replicaCount: 2
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi

auth-service:
  replicaCount: 1
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi

product-service:
  replicaCount: 1
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi

interaction-service:
  replicaCount: 1
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi

payment-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi

raffle-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi

postgres:
  resources:
    requests:
      cpu: 300m
      memory: 384Mi
    limits:
      cpu: 750m
      memory: 768Mi

redis:
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi
