global:
  namespace: dev

auth-service:
  secret:
    stringData:
      JWT_SECRET: "REPLACE_WITH_64_PLUS_RANDOM_CHARACTERS"
      ADMIN_PASSWORD: "REPLACE_WITH_ADMIN_PASSWORD"
      DEMO_PASSWORD: "REPLACE_WITH_DEMO_PASSWORD"

product-service:
  secret:
    stringData:
      DB_PASSWORD: "REPLACE_WITH_POSTGRES_PASSWORD"

interaction-service:
  secret:
    stringData:
      DB_PASSWORD: "REPLACE_WITH_POSTGRES_PASSWORD"
