replicaCount: 2

image:
  repository: ghcr.io/sneakertail/frontend
  tag: dev
  pullPolicy: Always

rollout:
  autoPromotionEnabled: false
  previewReplicaCount: 1
  scaleDownDelaySeconds: 30

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
