apiVersion: v1
kind: Service
metadata:
  name: auth-service-preview
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: auth-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
