{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: interaction-service-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
