apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  default.conf: |
{{ .Values.nginx.defaultConf | indent 4 }}
