apiVersion: v1
kind: Service
metadata:
  name: raffle-service-active
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: raffle-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
